[theme]
primaryColor = "#D76D77"  # Pink accent color
backgroundColor = "#5A1C71"  # Dark purple
secondaryBackgroundColor = "#3A1C71"  # Darker purple
textColor = "#FFFFFF"
font = "sans serif"

[server]
maxUploadSize = 5

[browser]
gatherUsageStats = false
